// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFileToIconPackFromPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFileToIconPackFromPath'](arg1, arg2, arg3);
}

export function AddFilesToIconPackFromDesktop(arg1) {
  return window['go']['main']['App']['AddFilesToIconPackFromDesktop'](arg1);
}

export function AddFilesToIconPackFromFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFilesToIconPackFromFolder'](arg1, arg2, arg3);
}

export function AddIconPack(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddIconPack'](arg1, arg2, arg3, arg4);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteIconPack(arg1) {
  return window['go']['main']['App']['DeleteIconPack'](arg1);
}

export function GetBase64Png() {
  return window['go']['main']['App']['GetBase64Png']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigField(arg1) {
  return window['go']['main']['App']['GetConfigField'](arg1);
}

export function GetIconFile() {
  return window['go']['main']['App']['GetIconFile']();
}

export function GetIconFolder() {
  return window['go']['main']['App']['GetIconFolder']();
}

export function GetIconPack(arg1) {
  return window['go']['main']['App']['GetIconPack'](arg1);
}

export function GetIconPackInfo() {
  return window['go']['main']['App']['GetIconPackInfo']();
}

export function GetLoadConfigPath() {
  return window['go']['main']['App']['GetLoadConfigPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function NeedsAdminPrivileges() {
  return window['go']['main']['App']['NeedsAdminPrivileges']();
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function RestartApplication(arg1, arg2) {
  return window['go']['main']['App']['RestartApplication'](arg1, arg2);
}

export function SaveConfigDialog() {
  return window['go']['main']['App']['SaveConfigDialog']();
}

export function SendNotification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3, arg4);
}

export function SetConfigField(arg1, arg2) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2);
}

export function SetIconPackInfo(arg1) {
  return window['go']['main']['App']['SetIconPackInfo'](arg1);
}

export function Test() {
  return window['go']['main']['App']['Test']();
}

export function Test2() {
  return window['go']['main']['App']['Test2']();
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}

export function UpdateAsAdmin(arg1) {
  return window['go']['main']['App']['UpdateAsAdmin'](arg1);
}
