// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDeletePngPath(arg1, arg2) {
  return window['go']['main']['App']['AddDeletePngPath'](arg1, arg2);
}

export function AddFileToIconPackFromPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFileToIconPackFromPath'](arg1, arg2, arg3);
}

export function AddFilesToIconPackFromDesktop(arg1) {
  return window['go']['main']['App']['AddFilesToIconPackFromDesktop'](arg1);
}

export function AddFilesToIconPackFromFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFilesToIconPackFromFolder'](arg1, arg2, arg3);
}

export function AddFilesToIconPackFromPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFilesToIconPackFromPath'](arg1, arg2, arg3);
}

export function AddIconPack(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddIconPack'](arg1, arg2, arg3);
}

export function AddTempPngPath(arg1, arg2) {
  return window['go']['main']['App']['AddTempPngPath'](arg1, arg2);
}

export function ApplyIconPack(arg1) {
  return window['go']['main']['App']['ApplyIconPack'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearDeletePngPaths() {
  return window['go']['main']['App']['ClearDeletePngPaths']();
}

export function ClearIconPackCache() {
  return window['go']['main']['App']['ClearIconPackCache']();
}

export function ClearTempPngPaths() {
  return window['go']['main']['App']['ClearTempPngPaths']();
}

export function CreateLastTab(arg1) {
  return window['go']['main']['App']['CreateLastTab'](arg1);
}

export function DeleteIconPack(arg1, arg2) {
  return window['go']['main']['App']['DeleteIconPack'](arg1, arg2);
}

export function Description(arg1) {
  return window['go']['main']['App']['Description'](arg1);
}

export function Destination(arg1) {
  return window['go']['main']['App']['Destination'](arg1);
}

export function ExportIconPack(arg1) {
  return window['go']['main']['App']['ExportIconPack'](arg1);
}

export function Ext(arg1) {
  return window['go']['main']['App']['Ext'](arg1);
}

export function GetBase64Png() {
  return window['go']['main']['App']['GetBase64Png']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigField(arg1) {
  return window['go']['main']['App']['GetConfigField'](arg1);
}

export function GetFileInfoFromDesktop(arg1) {
  return window['go']['main']['App']['GetFileInfoFromDesktop'](arg1);
}

export function GetFileInfoFromPaths(arg1, arg2) {
  return window['go']['main']['App']['GetFileInfoFromPaths'](arg1, arg2);
}

export function GetFilePath(arg1) {
  return window['go']['main']['App']['GetFilePath'](arg1);
}

export function GetIconFile() {
  return window['go']['main']['App']['GetIconFile']();
}

export function GetIconFiles() {
  return window['go']['main']['App']['GetIconFiles']();
}

export function GetIconFolder() {
  return window['go']['main']['App']['GetIconFolder']();
}

export function GetIconPack(arg1) {
  return window['go']['main']['App']['GetIconPack'](arg1);
}

export function GetIconPackList() {
  return window['go']['main']['App']['GetIconPackList']();
}

export function GetLoadConfigPath() {
  return window['go']['main']['App']['GetLoadConfigPath']();
}

export function GetTempPng(arg1) {
  return window['go']['main']['App']['GetTempPng'](arg1);
}

export function GetTempPngPath(arg1) {
  return window['go']['main']['App']['GetTempPngPath'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IconLocation(arg1) {
  return window['go']['main']['App']['IconLocation'](arg1);
}

export function ImportIconPack() {
  return window['go']['main']['App']['ImportIconPack']();
}

export function Name(arg1) {
  return window['go']['main']['App']['Name'](arg1);
}

export function NeedsAdminPrivileges() {
  return window['go']['main']['App']['NeedsAdminPrivileges']();
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function ReadLastTab() {
  return window['go']['main']['App']['ReadLastTab']();
}

export function RestartApplication(arg1, arg2) {
  return window['go']['main']['App']['RestartApplication'](arg1, arg2);
}

export function SaveConfigDialog() {
  return window['go']['main']['App']['SaveConfigDialog']();
}

export function SendNotification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3, arg4);
}

export function SetConfigField(arg1, arg2) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2);
}

export function SetIconPack(arg1) {
  return window['go']['main']['App']['SetIconPack'](arg1);
}

export function SetIconPackField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetIconPackField'](arg1, arg2, arg3, arg4);
}

export function SetIconPackFiles(arg1, arg2) {
  return window['go']['main']['App']['SetIconPackFiles'](arg1, arg2);
}

export function SetIconPackMetadata(arg1, arg2) {
  return window['go']['main']['App']['SetIconPackMetadata'](arg1, arg2);
}

export function UUID() {
  return window['go']['main']['App']['UUID']();
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}

export function UpdateAsAdmin(arg1) {
  return window['go']['main']['App']['UpdateAsAdmin'](arg1);
}
