// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigField(arg1:string):Promise<string>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetConfigField(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
