// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigField(arg1) {
  return window['go']['main']['App']['GetConfigField'](arg1);
}

export function GetLoadConfigPath() {
  return window['go']['main']['App']['GetLoadConfigPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function NeedsAdminPrivileges() {
  return window['go']['main']['App']['NeedsAdminPrivileges']();
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function RestartApplication(arg1, arg2) {
  return window['go']['main']['App']['RestartApplication'](arg1, arg2);
}

export function SaveConfigDialog() {
  return window['go']['main']['App']['SaveConfigDialog']();
}

export function SendNotification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3, arg4);
}

export function SetConfigField(arg1, arg2) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}

export function UpdateAsAdmin(arg1) {
  return window['go']['main']['App']['UpdateAsAdmin'](arg1);
}
