// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function CopyIcons(arg1) {
  return window['go']['main']['App']['CopyIcons'](arg1);
}

export function GetDesktopIcons() {
  return window['go']['main']['App']['GetDesktopIcons']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetIcon(arg1, arg2) {
  return window['go']['main']['App']['GetIcon'](arg1, arg2);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function RemoveProfile(arg1) {
  return window['go']['main']['App']['RemoveProfile'](arg1);
}

export function SaveIcon(arg1, arg2) {
  return window['go']['main']['App']['SaveIcon'](arg1, arg2);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SyncDesktop(arg1, arg2) {
  return window['go']['main']['App']['SyncDesktop'](arg1, arg2);
}

export function Test() {
  return window['go']['main']['App']['Test']();
}
