name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - "gh-pages"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.2
        with:
          path: build
